run:
  tests: false
  skip-dirs:
    - scripts
    - internal/otgrpc # it's a copy of https://github.com/grpc-ecosystem/grpc-opentracing
linters:
  enable-all: true
  disable:
    - nolintlint
    - gci
    - exhaustivestruct
    - wrapcheck
service:
  golangci-lint-version: 1.34.x
linters-settings:
  gocritic:
    enabled-tags:
      - style
      - experimental
      - performance
      - diagnostic
      - opinionated
