run:
  tests: false
  skip-dirs:
  - scripts
linters:
  enable-all: true
  disable:
   - goerr113
   - godot
   - nolintlint
   - gci
   - exhaustivestruct
   - wrapcheck
linters-settings:
  gocritic:
    enabled-tags:
      - style
      - experimental
      - performance
      - diagnostic
      - opinionated
